language: php

php:
  - 7.2

services:
  - mysql
  - redis-server

before_script:
  - cp .env.travis .env
  - mysql -e "create database testing;"
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm run prod
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit
